#!/bin/bash     # this line is to 高亮
####by Hongjun Hui
###Centos 7

#128.206.45.197

#echo 'hhdhf ALL=(ALL) ALL' >> /etc/sudoers
1. 文本启动
#systemctl set-default multi-user.target
2. 图形启动
#systemctl set-default graphical.target
3. 查看物理CPU的个数
#cat /proc/cpuinfo |grep "physical id"|sort |uniq|wc -l
4. 查看逻辑CPU的个数
#cat /proc/cpuinfo |grep "processor"|wc -l
5. 查看CPU是几核
#cat /proc/cpuinfo |grep "cores"|uniq
6. 查看CPU的主频
#cat /proc/cpuinfo |grep MHz|uniq
###########################################################################
###3/22/2015

##third source
#EPEL
sudo yum install epel-release
#ELRepo
sudo rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
sudo rpm -Uvh http://www.elrepo.org/elrepo-release-7.0-2.el7.elrepo.noarch.rpm
#yum-axelget
sudo yum install yum-axelget
#update all the softwares
sudo yum update

##change /etc/yum.repos.d/dropbox.repo(this should be done ervery time before use yum if the dropbox is updated).
$release ---->  20

#remove kernels
uname -r
rpm -qa | grep kernel
sudo yum remove kernel-.....

##Nvidia-detect
yum install nvidia-detect

##NTFS
sudo yum install ntfs-3g

##googel-chrome
#edit /etc/yum.repos.d/google-chrome.repo
[google-chrome]
name=google-chrome
baseurl=http://dl.google.com/linux/chrome/rpm/stable/$basearch
enabled=1
gpgcheck=1
gpgkey=https://dl-ssl.google.com/linux/linux_signing_key.pub
#sudo yum install google-chrome-stable

##unrar
sudo yum localinstall http://li.nux.ro/download/nux/dextop/el7/x86_64/unrar-5.0.12-2.el7.nux.x86_64.rpm

###23/3/2015
##GCC
sudo yum install compat-gcc-44
sudo yum install compat-gcc-44-c++
sudo yum install compat-gcc-44-gfortran

##cmake
sudo yum install cmake

##GMT 5.1.1
#http://gmtrac.soest.hawaii.edu/files/download?name=gmt-5.1.1-src.tar.gz
#ftp://ftp.soest.hawaii.edu/gshhg/gshhg-gmt-2.3.4.tar.gz
#ftp://ftp.soest.hawaii.edu/dcw/dcw-gmt-1.1.1.tar.gz
sudo yum install gcc-c++ libXt-devel libXaw-devel libXmu-devel libSM-devel
sudo yum install ghostscript cmake netcdf netcdf-devel gdal gdal-devel
tar -zxvf gmt-5.1.1-src.tar.gz
tar -zxvf dcw-gmt-1.1.1.tar.gz
tar -zxvf gshhg-gmt-2.3.4.tar.gz

cd gmt-5.1.1
cp cmake/ConfigUserTemplate.cmake cmake/ConfigUser.cmake
vi cmake/ConfigUser.cmake
set (CMAKE_INSTALL_PREFIX "/opt/GMT-5.1.1")
set (GMT_INSTALL_MODULE_LINKS FALSE)
set (GSHHG_ROOT "/home/hhdhf/software/GMT/gshhg-gmt-2.3.4")
set (COPY_GSHHG TRUE)
set (DCW_ROOT "/home/hhdhf/software/GMT/dcw-gmt-1.1.1")
set (COPY_DCW TRUE)

mkdir build
cd build/
cmake ..

make 
sudo make install

echo 'export GMT5HOME=/opt/GMT-5.1.1' >> ~/.bashrc
echo 'export PATH=${GMT5HOME}/bin:$PATH' >> ~/.bashrc
echo 'export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${GMT5HOME}/lib64' >> ~/.bashrc
exec $SHELL -l

##TauP
sudo yum install java
wget http://www.seis.sc.edu/downloads/TauP/TauP-2.1.2.tgz
tar -xvf TauP-2.1.2.tgz
sudo mv TauP-2.1.2 /opt

echo 'export TAUPHOME=/opt/TauP-2.1.2' >> ~/.bashrc
echo 'export PATH=${TAUPHOME}/bin:${PATH}' >> ~/.bashrc
source ~/.bashrc

###24/3/205

##SAC
sudo yum groupinstall 'Development Tools'
sudo yum install glibc ncurses-devel libSM-devel libICE-devel \
libXpm-devel libX11-devel zlib-devel
cd sac-101.4
sudo ./configure --prefix=/usr/local/sac
sudo make
sudo make install
echo 'export SACHOME=/usr/local/sac' >> ~/.bashrc
echo 'export SACAUX=$SACHOME/aux' >> ~/.bashrc
echo 'export PATH=$SACHOME/bin:$PATH' >> ~/.bashrc
echo 'export SAC_DISPLAY_COPYRIGHT=1' >> ~/.bashrc
#echo 'export SAC_PPK_LARGE_CROSSHAIRS=1' >> ~/.bashrc
echo 'export SAC_PPK_LARGE_CROSSHAIRS=0' >> ~/.bashrc
echo 'export SAC_USE_DATABASE=0' >> ~/.bashrc
source ~/.bashrc

###25/3/2015

##youtube-dl
sudo yum install youtube-dl

##mpich mpich-devel
sudo yum install mpich mpich-devel
echo 'export PATH=/usr/lib64/mpich/bin/:${PATH}' >> ~/.bashrc

##gnuplot
sudo yum install gnuplot

##SCOTCH
sudo yum install scotch

###3/4/2015

##2048-cli
sudo yum install 2048-cli

###17/8/2015

##some settings
set -o noclobber (set +o noclobber)

###3/9/2015

#remove google-chrome
sudo yum remove google-chrome-stable

###29/9/2015

#re-install google-chrome
rm -r ~/.config/google-chrome/
sudo yum install google-chrome-stable

###1/11/2015
#when google-chrome does not work, try to delete the .config/google-chrome/SingletonLock and reboot it again.

###10/11/2015
#edit ~/.vimrc (a setup file for vim)
set bg=dark
syntax on
set nu
set autoindent
set shiftwidth=6

###Parallel studio XE 2013 update3
#cd ~/softeware/..
sudo yum install gcc gcc-c++ gcc-gfortran pangox-compat-devel libunwind-devel
sudo yum install glibc.i686 libgcc.i686 libstdc++.i686
tar xvf filename
./install.sh
#active it using a licese file and input the full path to the license file (/home/hhdhf/software/Parallel_studio_XE_2013_update3)
#edit .bashrc
source /opt/intel/vtune_amplifier_xe_2013/amplxe-vars.sh quiet
source /opt/intel/inspector_xe_2013/inspxe-vars.sh quiet
source /opt/intel/advisor_xe_2013/advixe-vars.sh quiet
source /opt/intel/bin/compilervars.sh intel64

###19/11/2015
## ffmpeg (a multimedia framework)
git clone git://source.ffmpeg.org/ffmpeg.git ffmpeg
cd ffmpeg
./configure --disable-yasm
make
sudo make install

##PCRE (Perl compatible regular expressions, needed by Octave)
sudo yum install pcre-devel
##GNU Octave (needed by Radiative3D) 
sudo yum-builddep octave

## edit the .bashrc file
#GiD
export GIDHOME=/opt/gid12
export PATH=$GIDHOME:${PATH}


###Matlab
mount -o loop matlab.iso /mnt/
#edit /usr/share/applicatons/Matlab.desktop
[Desktop Entry]
Type=Application
Name=Matlab
GenericName=Matlab 2012a
Comment=Matlab: The Language of Technical Computing
Exec=sh /usr/local/MATLAB/R2012a/bin/matlab -desktop
Icon=/usr/local/MATLAB/R2012a/Matlab.png
Terminal=false
Categories=Development;Matlab;

export MATLABHOME=/usr/local/MATLAB/R2012a
export PATH=$MATLABHOME/bin/:${PATH}

### Jabref
#for fedora
cd /etc/yum.repos.d/
sudo wget http://download.opensuse.org/repositories/home:cornell_vrdc/Fedora_20/home:cornell_vrdc.repo
sudo yum install jabref
#for centos 7
cd /etc/yum.repos.d/
sudo wget http://download.opensuse.org/repositories/home:cornell_vrdc/CentOS_7/home:cornell_vrdc.repo
sudo yum install jabref

### Install Screen
sudo yum install screen
# screen -S job_name
# screen -r job_name
# screen -ls

### keygen (ssh no need password)
ssh-keygen
ssh-copy-id -i ~/.ssh/id_rsa.pub mica.geosc.missouri.edu
ssh-copy-id -i ~/.ssh/id_rsa.pub halite.missouri.edu
